use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:unumdesign/unum-ios-ui-specs.git'

target 'UNUMColorPicker_Example' do
  pod 'UNUMColorPicker', :path => '../'
  pod 'SwiftLint'
  pod 'unum-ios-ui', :git => 'git@github.com:unumdesign/unum-ios-ui.git', :branch => 'develop'

  target 'UNUMColorPicker_Tests' do
    inherit! :search_paths

    
  end
end
